### ISSUE TITLE
download all task and activities even stop process

### ISSUE THREAD

**Issue by johnfelipe** [miurla/babyagi-ui#132] opened 2023-07-18 12:42 UTC
before i have this:

[Construcción_de_componentes_de_Mapeo_de_Datos_desde_un_XML_de_un_Robot_virtual_de_Mapeo_y_Transformación_usando_Azure_Batch.txt](https://github.com/miurla/babyagi-ui/files/12080500/Construccion_de_componentes_de_Mapeo_de_Datos_desde_un_XML_de_un_Robot_virtual_de_Mapeo_y_Transformacion_usando_Azure_Batch.txt)

some little messed

but now with latest version i need wait to finish iteration for download complete file
im trying using my own deploy
https://babyagi-ui-fork-3pgjnkxox-johnfelipe.vercel.app/es?vercelToolbarCode=E_cKnY3Z4Mv5d4e

but i cant download a good AGI tasks file
Can u help me?

**Comment by johnfelipe** [comment] 2023-07-19 12:24
For example if u use older version of your app here:
babyagiui-pthj4kowa-johnfelipe.vercel.app

all working
little messed
but can download when stop before complete iterations, etc
Pls fix recent or latest version for use your awsome app

**Comment by johnfelipe** [comment] 2023-07-19 12:28
[1._Creación_de_la_lógica_de_lectura_y_configuración_de_parametrización____-_Implementar_la_lectura_de_la_tabla_de_parámetros____-_Construir_objetos_contenedores_de_parámetros__Batch,_email,_storage.txt](https://github.com/miurla/babyagi-ui/files/12094849/1._Creacion_de_la_logica_de_lectura_y_configuracion_de_parametrizacion____-_Implementar_la_lectura_de_la_tabla_de_parametros____-_Construir_objetos_contenedores_de_parametros__Batch._email._storage.txt)

![SNAG-0307](https://github.com/miurla/babyagi-ui/assets/428820/13ef279e-7edd-4f9d-b3b1-b3dda77028e2)

i simple stop 5 min later of begin and show me txt downloable

**Comment by johnfelipe** [comment] 2023-07-19 12:36
pls review this video:

https://drive.google.com/file/d/1AcBFzxYRVMskjxLV0u1z66PBXjjaQja0/view?usp=drivesdk

is important PIN feature, dont delete of latest version
And pls allow download txt with tasks and answers if iterations dont complete

Or tell me how solve this?

**Comment by miurla** [comment] 2023-07-19 15:56
Thank you for the explanation in the video. There are 2 issues, so I'll answer each one separately.

1. PIN feature 
This function has been discontinued because BabyDeer has become the main agent and it is not used much. Recently, I have not been updating anything related to the original BabyAGI, so if you really need it, you might want to use an older version.

2. Download text 
I stopped and checked in the latest version, and confirmed that I could download it as shown in the screenshot. What differences are there between the web and the text file? Please tell me the details of the differences.


<img width="1585" alt="image" src="https://github.com/miurla/babyagi-ui/assets/3412179/76da6c8a-ba0c-4752-a255-38155afbd18b">

**Comment by miurla** [comment] 2023-07-22 00:25
> Can u share me steps for try BABYELFAGI

If you revert the following commit, the PIN function will be restored.
https://github.com/miurla/babyagi-ui/commit/7e5a18c6cd01899141dc8d98456169ba79e8bfa1


> there i only BABYDEER

I deployed it a while ago.


If this issue has been resolved, please close it.

**Closed** 2023-07-22 01:30 UTC
