### ISSUE TITLE
Uncaught (in promise) Error - Agente: BabyElfAGI

### ISSUE THREAD

**Issue by johnfelipe** [miurla/babyagi-ui#141] opened 2023-07-23 16:11 UTC
![SNAG-0398](https://github.com/miurla/babyagi-ui/assets/428820/6e22ef80-c972-47cc-b4e0-fd0a264eba53)

`Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

**Comment by miurla** [comment] 2023-07-23 23:38
It seems that you are receiving a 429 error from the OpenAI API. This indicates that you have reached the rate limit. https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

Could you please check the following items?

You are sharing your API key with other users or applications.
You are using a free plan that has a low rate limit.

**Comment by johnfelipe** [comment] 2023-07-25 19:16
Bro i have new API, only created for this, and still with error:

```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by miurla** [comment] 2023-07-26 00:28
Has the error from OpenAI API been resolved?

<img width="648" alt="image" src="https://github.com/miurla/babyagi-ui/assets/3412179/c63179a3-cb10-4ddd-9f79-1fa4682bc939">

**Comment by johnfelipe** [comment] 2023-07-26 11:54
with not pay account and with pay account have issues, pls view this video:

https://drive.google.com/file/d/1R8pLQedx5PO60AvFLhIr0JbawNPpRWYz/view?usp=drivesdk

**Comment by miurla** [comment] 2023-07-26 13:05
#150 

There was a case where unusable skills were being generated as tasks. 
Can you check if I’ve made the corrections?

**Comment by johnfelipe** [comment] 2023-07-26 17:16
https://drive.google.com/file/d/11dHrF2pBN1Bv0pY8Itq0Dogd2-iV3o0n/view?usp=drivesdk

with free acount not works
with pay account works but results havent context with question

**Comment by miurla** [comment] 2023-07-27 01:59
> with free acount not works

It would not work on this account as there seems to be no free credit.

> with pay account works but results havent context with question

- You've access to the OpenAI API in your pay account, so it seems to be resolved as far as the issue is concerned.
- The missing Context seems to be an error with the newly added WebLoader skill.  I’ll open this as a separate issue. It's loading on my end, so please try again or try a different URL. This page appears to be an unreadable page in scrape.

<img width="855" alt="image" src="https://github.com/miurla/babyagi-ui/assets/3412179/4d22bea7-4d87-491b-94c9-d4b83d9cd7dc">

**Comment by miurla** [comment] 2023-08-03 06:25
This issue itself is closed as it has been resolved. The remaining bugs will be passed on to another issue.

**Closed by miurla** 2023-08-03 06:25 UTC
