### ISSUE TITLE
Error in spanish acute and other things

### ISSUE THREAD

**Issue by johnfelipe** [miurla/babyagi-ui#125] opened 2023-07-04 23:46 UTC
[Crear_4_sprints_para_ser_montado_en_Azure_Devops_Cada_sprint_con_10_dias_habiles_o_2_semanas_calendario_Listar_actividades_y_tareas_por_sprint_Cada_actividad_y_tarea_con_numero_de_horas_de_esfuerzo_para_dos_desar.txt](https://github.com/miurla/babyagi-ui/files/11952703/Crear_4_sprints_para_ser_montado_en_Azure_Devops_Cada_sprint_con_10_dias_habiles_o_2_semanas_calendario_Listar_actividades_y_tareas_por_sprint_Cada_actividad_y_tarea_con_numero_de_horas_de_esfuerzo_para_dos_desar.txt)

![SNAG-0159](https://github.com/miurla/babyagi-ui/assets/428820/db4d5ac1-a50c-40ca-b78d-b646051863b5)

and markdown to:

![SNAG-0160](https://github.com/miurla/babyagi-ui/assets/428820/9e281205-79a0-4c4c-9f3b-7a01b9b40308)

How can contribute or collaborate for translate corrrectly to spanish?

**Comment by johnfelipe** [comment] 2023-07-05 00:03
in webpage is ok:


https://github.com/miurla/babyagi-ui/assets/428820/7e4abf5f-f02c-4532-b3f8-25ce905cb72b

**Comment by miurla** [comment] 2023-07-06 00:30
@johnfelipe  Thank you for your report.

It seems that the issue is not with the translation, as everything appears correctly on the webpage. Instead, it appears to be an encoding issue when the text is downloaded as a file. I didn't encounter this issue on my Mac environment.

I've merged a pull request that addresses this encoding issue. Could you please check if the issue has been resolved on your end?

PR: #127

**Comment by johnfelipe** [comment] 2023-07-06 00:32
I will do it in my morning tomorrow

**Closed** 2023-07-06 14:37 UTC
