### ISSUE TITLE
BabyDeer + GPT-4 >> ERROR_CREATING_TASKS

### ISSUE THREAD

**Issue by regismvargas** [miurla/babyagi-ui#118] opened 2023-06-26 21:32 UTC
I received the message "ERROR_CREATING_TASKS" when trying to use GPT-4. GPT-3 it's working fine.

![image](https://github.com/miurla/babyagi-ui/assets/46408091/176b1150-5deb-4525-8a14-8b1e6828e2f7)

**Comment by miurla** [comment] 2023-06-27 01:58
In this case, the issue is mostly caused by the API key not having access to GPT-4. Do you have the access rights?
https://platform.openai.com/docs/models/gpt-4

**Comment by miurla** [comment] 2023-07-15 04:35
GPT-4 has been released to everyone, so I will close this issue.

**Closed by miurla** 2023-07-15 04:35 UTC
